//COMPONENTS
import Head from 'next/head';
import Link from 'next/link';

import '../styles/globals.css'
import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Stefano Stortini Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
      </Head>
      <nav className="flex sticky top-0 items-center justify-between flex-wrap p-8 bg-white z-10">
        <Link href='/'>
          <h1 className=' text-4xl italic font-bold text-orange-500'>Stefano Stortini</h1>
        </Link>
        <ul className="flex  font-semibold text-gray-600">
          <li className='mx-8 hover:text-orange-500 border-b-4 border-t-4 border-white hover:border-b-orange-500 transition-colors'><Link href='/skills'>SKILLS</Link></li>
          <li className='mx-8 hover:text-orange-500 border-b-4 border-t-4 border-white hover:border-b-orange-500 transition-colors'><Link href='/works'>WORKS</Link></li>
          <li className='mx-8 hover:text-orange-500 border-b-4 border-t-4 border-white hover:border-b-orange-500 transition-colors'><Link href='/cv'>CV</Link></li>
        </ul>
        <button type="button" className=" text-white bg-gradient-to-r hover:bg-gradient-to-br from-gray-500 via-gray-600 to-gray-700 hover:from-orange-500 hover:via-orange-600 hover:to-orange-700 shadow-md hover:shadow-orange-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
          CONTACT ME
        </button>
      </nav>
      <Component {...pageProps} />
    </div>
  )
}
